# Generated by Django 5.1.5 on 2025-02-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cart_order_orderitem_order_food_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='ordered_at',
        ),
    ]
