# Generated by Django 5.1.5 on 2025-02-09 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_created_at_order_ordered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_items',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app1.order'),
        ),
    ]
