# Generated by Django 5.1.5 on 2025-02-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('show_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('seats', models.PositiveIntegerField()),
            ],
        ),
    ]
