# Generated by Django 5.1.5 on 2025-02-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_showbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='music_events/')),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
