# Generated by Django 5.1.5 on 2025-02-26 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicevent',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='musicevent',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
