# Generated by Django 5.1.5 on 2025-02-26 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_name_musicevent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='showbooking',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
